import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHmac} from 'node:crypto';
import {fixture,subscription,message,KEY,SECRET} from './fixtures.mjs';
import {Bridge} from '../src/bridge.mjs';
import {Store} from '../src/store.mjs';
import {handleRpc,createEndpoint} from '../src/mcp.mjs';
import {publicAddress,validateDestination,callbackUrl,sign,secretKey,createPinnedHttpsTransport} from '../src/security.mjs';
import {normalizePoll,replyBody} from '../src/ilink-contract.mjs';

test('MCP discovery and event definition require owner authentication',async t=>{const f=await fixture(t);const rpc={jsonrpc:'2.0',id:1,method:'server/discover'};assert.equal((await handleRpc(f.bridge,'stranger',rpc)).error.message,'Unauthorized');const r=await handleRpc(f.bridge,'principal',rpc);assert.deepEqual(r.result.supportedVersions,['2026-07-28']);assert.ok(r.result.capabilities.events);assert.equal((await handleRpc(f.bridge,'principal',{...rpc,method:'events/list'})).result.events[0].delivery[0],'webhook');});
test('end to end synthetic event + read + idempotent reply',async t=>{const f=await fixture(t);const s=await f.bridge.subscribe('principal',subscription());await f.bridge.pollOnce();await f.bridge.pump();assert.equal(f.callbacks.length,2);const event=JSON.parse(f.callbacks[1].body);assert.equal(event.data.text,'你好，dot');assert.equal(f.callbacks[1].headers['X-MCP-Subscription-Id'],s.id);assert.equal(event.cursor,null);assert.equal(f.bridge.read('principal',event.data.message_id).text,'你好，dot');assert.ok(!JSON.stringify(event).includes('synthetic-context'));const args={message_id:event.data.message_id,text:'你好！',idempotency_key:'reply-1'};assert.equal((await f.bridge.reply('principal',args)).state,'sent');await f.bridge.reply('principal',args);assert.equal(f.sent.length,1);assert.equal(f.sent[0].contextToken,'synthetic-context');await assert.rejects(f.bridge.reply('principal',{...args,text:'changed'}),/conflict/);await assert.rejects(f.bridge.reply('principal',{...args,to:'stranger'}),/invalid_reply/);});
test('sender allowlist default deny, no bot/group/outbound/wrong bot loops',async t=>{const f=await fixture(t);await f.bridge.ingest({cursor:'a',messages:[message({sender:'stranger'}),message({role:'assistant'}),message({group:true}),message({direction:'outbound'}),message({bot:'other'})]});assert.equal(f.bridge.status('principal').inboxCount,0);const b=new Bridge({...f.config,allowedSenders:[]});await b.ingest({cursor:'b',messages:[message()]});assert.equal(b.status('principal').inboxCount,0);});
test('durable cursor, inbox dedup, outbox and subscription survive restart encrypted',async t=>{const f=await fixture(t);await f.bridge.subscribe('principal',subscription());await f.bridge.pollOnce();const bytes=await readFile(f.dir+'/state.enc','utf8');for(const s of ['你好','synthetic-context',SECRET])assert.ok(!bytes.includes(s));const b=await f.restart();assert.equal(f.store.state.cursor,'next');await b.pollOnce();assert.equal(b.status('principal').inboxCount,1);await b.pump();assert.equal(b.status('principal').pendingEvents,0);});
test('single store owner lock, key required, persisted identity isolation',async t=>{const f=await fixture(t);await f.bridge.pollOnce();await assert.rejects(Store.open(f.dir,KEY),/store_already_open/);assert.throws(()=>new Bridge({...f.config,owner:'someone'}),/identity_mismatch/);assert.throws(()=>new Bridge({...f.config,mode:'production'}),/live_mode/);});
test('subscription create/refresh/unsubscribe idempotence and finite TTL',async t=>{const f=await fixture(t),p=subscription();const a=await f.bridge.subscribe('principal',p);const b=await f.bridge.subscribe('principal',{...p,ttlMs:1000});assert.equal(a.id,b.id);assert.equal(f.callbacks.length,1);assert.equal(Object.keys(f.store.state.subscriptions).length,1);const q=structuredClone(p);delete q.delivery.secret;await f.bridge.unsubscribe('principal',q);await f.bridge.unsubscribe('principal',q);assert.equal(Object.keys(f.store.state.subscriptions).length,0);await assert.rejects(f.bridge.subscribe('stranger',p),/unauthorized/);});
test('verification must echo challenge; failure never activates',async t=>{const f=await fixture(t,{transport:async()=>({status:200,body:'{"challenge":"wrong"}'})});await assert.rejects(f.bridge.subscribe('principal',subscription()),e=>e.rpcCode===-32015&&e.reason==='challenge_failed');assert.equal(Object.keys(f.store.state.subscriptions).length,0);});
test('callback redirect is rejected even with challenge echo',async t=>{const f=await fixture(t,{transport:async(_u,r)=>({status:302,body:JSON.stringify({challenge:JSON.parse(r.body).challenge})})});await assert.rejects(f.bridge.subscribe('principal',subscription()),e=>e.rpcCode===-32015);});
test('callback expiry, access revocation and unsubscribe stop deliveries',async t=>{const f=await fixture(t);await f.bridge.subscribe('principal',{...subscription(),ttlMs:1});await f.bridge.pollOnce();f.advance(2);await f.bridge.pump();assert.equal(f.callbacks.length,1);f.revoke();assert.throws(()=>f.bridge.read('principal',Object.keys(f.store.state.inbox)[0]),/unauthorized/);await assert.rejects(f.bridge.pump(),/unauthorized/);});
test('bounded retries preserve event ID with fresh signatures and backoff',async t=>{const f=await fixture(t);await f.bridge.subscribe('principal',subscription());await f.bridge.pollOnce();const events=[];f.bridge.transport=async(_u,r)=>{events.push(r);return {status:503,body:''};};await f.bridge.pump();await f.bridge.pump();assert.equal(events.length,1);for(let i=0;i<5;i++){f.advance(20000);await f.bridge.pump();}assert.equal(events.length,5);assert.equal(new Set(events.map(r=>r.headers['webhook-id'])).size,1);assert.notEqual(events[0].headers['webhook-signature'],events[1].headers['webhook-signature']);assert.equal(f.bridge.status('principal').deadEvents,1);});
test('410 and 413 are terminal, no retry',async t=>{for(const status of [410,413]){const f=await fixture(t);await f.bridge.subscribe('principal',subscription());await f.bridge.pollOnce();let count=0;f.bridge.transport=async()=>{count++;return {status,body:''};};await f.bridge.pump();f.advance(1e6);await f.bridge.pump();assert.equal(count,1);}});
test('secret rotation emits both signatures during window',async t=>{const f=await fixture(t),p=subscription();await f.bridge.subscribe('principal',p);p.delivery.secret='whsec_'+Buffer.alloc(32,12).toString('base64');await f.bridge.subscribe('principal',p);await f.bridge.pollOnce();await f.bridge.pump();assert.equal(f.callbacks.at(-1).headers['webhook-signature'].split(' ').length,2);});
test('reply unknown result is not retried, even after restart',async t=>{const f=await fixture(t);await f.bridge.pollOnce();let attempts=0;f.bridge.adapter.reply=async()=>{attempts++;throw Error('lost response');};const a={message_id:Object.keys(f.store.state.inbox)[0],text:'hi',idempotency_key:'one'};assert.equal((await f.bridge.reply('principal',a)).state,'unknown');await f.bridge.reply('principal',a);await f.restart();await f.bridge.reply('principal',a);assert.equal(attempts,1);});
test('expired context or invented message cannot be replied to',async t=>{const f=await fixture(t);await f.bridge.pollOnce();const a={message_id:Object.keys(f.store.state.inbox)[0],text:'hi',idempotency_key:'one'};f.advance(3600001);await assert.rejects(f.bridge.reply('principal',a),/context_unavailable/);await assert.rejects(f.bridge.reply('principal',{...a,message_id:'invented'}),/context_unavailable/);});
test('concurrent polling rejected and malformed batch does not advance cursor',async t=>{let done;const f=await fixture(t);f.bridge.adapter.poll=()=>new Promise(r=>{done=r;});const first=f.bridge.pollOnce();await assert.rejects(f.bridge.pollOnce(),/already_running/);done({cursor:'bad',messages:[{}]});await assert.rejects(first,/invalid_message/);assert.equal(f.store.state.cursor,'');});
test('SSRF: HTTPS only, explicit hosts, no IP literals/ports/userinfo/fragments',()=>{for(const u of ['http://callback.example.test/a','https://127.0.0.1/a','https://callback.example.test:444/a','https://user@callback.example.test/a','https://callback.example.test/a#b','https://evil.test/'])assert.throws(()=>callbackUrl(u,['callback.example.test']));});
test('SSRF: connection-time DNS rejects local, private, reserved, mapped IPv6 and mixed answers',async()=>{for(const ip of ['127.0.0.1','10.1.2.3','169.254.169.254','172.31.1.1','192.168.0.1','100.100.100.200','0.0.0.0','224.1.2.3','198.18.0.1','203.0.113.1','::1','::ffff:127.0.0.1']){assert.equal(publicAddress(ip),false,ip);await assert.rejects(validateDestination('https://callback.example.test/a',['callback.example.test'],async()=>[{address:'8.8.8.8'},{address:ip}]),/address_rejected/);}assert.equal(publicAddress('8.8.8.8'),true);});
test('Standard Webhooks exact byte signing and strict key validation',()=>{const body='{"text":"你好"}',id='evt_1',ts='1801300000';const expected='v1,'+createHmac('sha256',Buffer.alloc(32,9)).update(id+'.'+ts+'.'+body).digest('base64');assert.equal(sign(SECRET,id,ts,body),expected);for(const secret of ['abc','whsec_AA==','whsec_!'])assert.throws(()=>secretKey(secret));});
test('HTTP endpoint default denies auth, enforces TLS, path, content and size',async t=>{const f=await fixture(t),input={method:'POST',path:'/mcp',headers:{'content-type':'application/json',accept:'application/json, text/event-stream','mcp-protocol-version':'2026-07-28','mcp-method':'tools/list'},secure:true,body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/list',params:{_meta:{'io.modelcontextprotocol/protocolVersion':'2026-07-28','io.modelcontextprotocol/clientCapabilities':{}}}})};assert.equal((await createEndpoint(f.bridge)(input)).status,401);const endpoint=createEndpoint(f.bridge,{authenticate:async()=> 'principal'});assert.equal((await endpoint(input)).status,200);assert.equal((await endpoint({...input,secure:false})).status,400);assert.equal((await endpoint({...input,body:'x'.repeat(262145)})).status,413);assert.equal((await endpoint({...input,body:'{' })).status,400);});
test('iLink pure mapping refuses errors, bots/groups, unsafe IDs and omits missing contexts',()=>{assert.throws(()=>normalizePoll({ret:-14},'b'),/session_expired/);const m={message_id:1,from_user_id:'owner',to_user_id:'b',message_type:1,message_state:2,context_token:'ctx',create_time_ms:1801300000000,item_list:[{type:1,text_item:{text:'hi'}}]};const r=normalizePoll({ret:0,msgs:[m,{...m,message_type:2},{...m,group_id:'g'},{...m,context_token:null}],get_updates_buf:'next'},'b');assert.equal(r.messages.length,1);assert.equal(replyBody({to:'owner',contextToken:'ctx',text:'hi',clientId:'stable'},'0.1.0').msg.context_token,'ctx');});
test('invalid owner content quarantined while valid messages and cursor commit',async t=>{const f=await fixture(t);await f.bridge.subscribe('principal',subscription());await f.bridge.ingest({cursor:'next',messages:[message(),message({id:'2',timestamp:1e100})]});assert.equal(f.bridge.status('principal').inboxCount,1);assert.equal(f.store.state.cursor,'next');assert.equal(f.bridge.status('principal').pendingEvents,1);assert.equal(f.bridge.status('principal').quarantinedMessages,1);});
test('unsubscribe then resubscribe never revives old pending jobs',async t=>{const f=await fixture(t),p=subscription();await f.bridge.subscribe('principal',p);await f.bridge.pollOnce();const q=structuredClone(p);delete q.delivery.secret;await f.bridge.unsubscribe('principal',q);await f.bridge.subscribe('principal',p);await f.bridge.pump();assert.equal(f.callbacks.length,1);assert.equal(f.bridge.status('principal').pendingEvents,0);});
test('expired subscription recreation does not replay old queued events',async t=>{const f=await fixture(t);await f.bridge.subscribe('principal',{...subscription(),ttlMs:1});await f.bridge.pollOnce();f.advance(2);await f.bridge.subscribe('principal',subscription());await f.bridge.pump();assert.equal(f.callbacks.length,1);});
test('async/Promise authorizer fails closed rather than granting access',async t=>{const f=await fixture(t,{authorize:async()=>false});assert.throws(()=>f.bridge.status('principal'),/unauthorized/);await assert.rejects(f.bridge.subscribe('principal',subscription()),/unauthorized/);});
test('crash at final webhook attempt cannot exceed retry bound',async t=>{const f=await fixture(t);await f.bridge.subscribe('principal',subscription());await f.bridge.pollOnce();const job=Object.values(f.store.state.outbox)[0];job.attempts=5;await f.store.save();await f.restart();await f.bridge.pump();assert.equal(f.callbacks.length,1);assert.equal(f.bridge.status('principal').deadEvents,1);});
test('same-secret refresh preserves previous signing-key rotation window',async t=>{const f=await fixture(t),p=subscription();await f.bridge.subscribe('principal',p);p.delivery.secret='whsec_'+Buffer.alloc(32,12).toString('base64');await f.bridge.subscribe('principal',p);await f.bridge.subscribe('principal',p);await f.bridge.pollOnce();await f.bridge.pump();assert.equal(f.callbacks.at(-1).headers['webhook-signature'].split(' ').length,2);});

test('HTTPS timeout bounds DNS resolution before socket creation',async()=>{const transport=createPinnedHttpsTransport(['callback.example.test'],async()=>new Promise(()=>{}),5);await assert.rejects(transport('https://callback.example.test/a',{headers:{},body:'{}'}),/timeout/);});
test('disk failure poisons instance so uncommitted in-memory cursor cannot be used',async t=>{const f=await fixture(t);f.store.dir=f.dir+'/absent';await assert.rejects(f.bridge.pollOnce(),/ENOENT/);assert.throws(()=>f.bridge.status('principal'),/storage_unavailable/);await assert.rejects(f.bridge.pollOnce(),/storage_unavailable/);});

test('disallowed oversized text cannot poison an owner batch',async t=>{const f=await fixture(t);await f.bridge.ingest({cursor:'next',messages:[message({id:'evil',sender:'stranger',text:'x'.repeat(100000)}),message()]});assert.equal(f.store.state.cursor,'next');assert.equal(f.bridge.status('principal').inboxCount,1);assert.equal(f.bridge.status('principal').quarantinedMessages,0);});

test('reply idempotency canonicalizes JSON argument order',async t=>{const f=await fixture(t);await f.bridge.pollOnce();const message_id=Object.keys(f.store.state.inbox)[0];await f.bridge.reply('principal',{message_id,text:'hello',idempotency_key:'same'});await f.bridge.reply('principal',{idempotency_key:'same',text:'hello',message_id});assert.equal(f.sent.length,1);});
