import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {Readable} from 'node:stream';
import {createRestrictedHttpsTransport} from '../src/security.mjs';
import {createRequestHandler} from '../src/http-server.mjs';
function requester({status=200,response='{}',seen=[]}={}){return(url,options,callback)=>{seen.push({url:String(url),options});const req=new EventEmitter();req.end=body=>{seen.at(-1).body=body;queueMicrotask(()=>{const res=new Readable({read(){}});res.statusCode=status;callback(res);res.push(response);res.push(null);});};return req;};}
test('HTTPS transport pins validated address, preserves SNI and certificate checks',async()=>{const seen=[];const transport=createRestrictedHttpsTransport({allowedHosts:['allowed.example.invalid'],resolve:async()=>[{address:'8.8.8.8'}],requestImpl:requester({seen})});await transport('https://allowed.example.invalid/a',{headers:{},body:'{}'});assert.equal(seen[0].options.servername,'allowed.example.invalid');assert.equal(seen[0].options.rejectUnauthorized,true);assert.equal(seen[0].options.headers.host,'allowed.example.invalid');let address;seen[0].options.lookup('allowed.example.invalid',{},(_e,a)=>{address=a;});assert.equal(address,'8.8.8.8');assert.equal(seen[0].options.agent,false);});
test('DNS is revalidated on every connection; rebind to private address rejected',async()=>{let dns=0;const seen=[];const transport=createRestrictedHttpsTransport({allowedHosts:['allowed.example.invalid'],resolve:async()=>[{address:++dns===1?'8.8.8.8':'127.0.0.1'}],requestImpl:requester({seen})});await transport('https://allowed.example.invalid/a',{body:'{}'});await assert.rejects(transport('https://allowed.example.invalid/a',{body:'{}'}),/address_rejected/);assert.equal(seen.length,1);});
test('HTTPS transport never follows redirect and bounds response',async()=>{const seen=[];let transport=createRestrictedHttpsTransport({allowedHosts:['allowed.example.invalid'],resolve:async()=>[{address:'8.8.8.8'}],requestImpl:requester({status:302,seen})});await assert.rejects(transport('https://allowed.example.invalid/a',{body:'{}'}),/redirect_rejected/);assert.equal(seen.length,1);transport=createRestrictedHttpsTransport({allowedHosts:['allowed.example.invalid'],resolve:async()=>[{address:'8.8.8.8'}],requestImpl:requester({response:'x'.repeat(20)}),maxResponseBytes:10});await assert.rejects(transport('https://allowed.example.invalid/a',{body:'{}'}),/response_failed/);});
test('external abort cancels pending DNS without socket attempt',async()=>{const controller=new AbortController();let sockets=0;const transport=createRestrictedHttpsTransport({allowedHosts:['allowed.example.invalid'],resolve:async()=>new Promise(()=>{}),requestImpl:()=>{sockets++;}});const pending=transport('https://allowed.example.invalid/a',{body:'{}',signal:controller.signal});controller.abort();await assert.rejects(pending,/aborted/);assert.equal(sockets,0);});
async function http({host='bridge.example.invalid',encrypted=true,body='{}',headers={},path='/mcp',method='POST'}={}){let calls=0,output;const req=Readable.from([Buffer.from(body)]);req.socket={encrypted};req.headers={host,...headers};req.url=path;req.method=method;const res=new EventEmitter();res.destroyed=false;res.writeHead=(status,h)=>{output={status,headers:h};};res.end=body=>{output.body=body;};await createRequestHandler({publicUrl:'https://bridge.example.invalid/mcp',application:{handle:async input=>{calls++;assert.equal(input.secure,true);return {status:200,body:'{}'};}}})(req,res);return {calls,output};}
test('HTTP host/TLS checks ignore spoofed forwarding flags',async()=>{assert.equal((await http({encrypted:false,headers:{'x-forwarded-proto':'https'}})).calls,0);assert.equal((await http({host:'evil.invalid'})).calls,0);assert.equal((await http()).calls,1);});
test('HTTP streaming and declared-length caps reject body before application',async()=>{let r=await http({body:'x'.repeat(262145)});assert.equal(r.output.status,413);assert.equal(r.calls,0);r=await http({headers:{'content-length':'999999'}});assert.equal(r.output.status,413);assert.equal(r.calls,0);assert.equal((await http({path:'/mcp?token=secret'})).calls,0);});

// The query exception is only the fixed OAuth protocol callback, never API tokens.
test('HTTP query exception is restricted to exact GET OAuth callback',async()=>{
 assert.equal((await http({path:'/admin/oauth/callback?code=synthetic&state=synthetic',method:'GET'})).calls,1);
 for(const path of ['/admin?code=x','/mcp?code=x','/admin/oauth/callback/extra?code=x','//evil.invalid/admin/oauth/callback?code=x','/admin/oauth/callback?code=x#fragment'])assert.equal((await http({path,method:'GET'})).calls,0);
 assert.equal((await http({path:'/admin/oauth/callback?code=x',method:'POST'})).calls,0);
});
